# Generated by Django 2.0.6 on 2018-12-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Penilaian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblrefstatuspenilaian',
            name='StatusPenilaian',
            field=models.CharField(default=1, max_length=50, verbose_name='StatusPenilaian'),
            preserve_default=False,
        ),
    ]
