# Generated by Django 2.1.2 on 2018-12-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Penilaian', '0002_auto_20181214_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refstatuspenilaian',
            name='Keterangan',
            field=models.CharField(max_length=200, verbose_name='Keterangan'),
        ),
    ]
