# Generated by Django 2.0.6 on 2018-12-05 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pentadbir', '0004_uperanan'),
        ('Urusetia', '0009_auto_20181205_1508'),
        ('Penilaian', '0002_tblrefstatuspenilaian_statuspenilaian'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblJadual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TarikhMula', models.DateField(max_length=60, verbose_name='TarikhMula')),
                ('TarikhTamat', models.DateField(max_length=60, verbose_name='TarikhTamat')),
                ('Status', models.IntegerField(default=1, verbose_name='Status')),
                ('AuditeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.TblAuditee')),
                ('PenggunaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.UProfil')),
                ('SesiID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.TblSesi')),
                ('StatusPenilaianID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Penilaian.TblRefStatusPenilaian')),
            ],
        ),
    ]
