# Generated by Django 2.0.6 on 2018-12-05 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pentadbir', '0004_uperanan'),
        ('Penilaian', '0004_auto_20181205_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAuditTrailJadual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TarikhTransaksi', models.DateField(max_length=60, verbose_name='TarikhTransaksi')),
                ('Tindakan', models.CharField(max_length=50, verbose_name='Tindakan')),
                ('JadualID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Penilaian.TblJadual')),
                ('PenggunaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.UProfil')),
            ],
        ),
    ]
