# Generated by Django 2.0.6 on 2018-12-05 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Penilaian', '0005_tblaudittrailjadual'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeskripsiAttachment', models.CharField(max_length=50, verbose_name='DeskripsiAttachment')),
                ('Path', models.CharField(max_length=50, verbose_name='Path')),
            ],
        ),
        migrations.CreateModel(
            name='TblRefAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JenisKategori', models.CharField(max_length=50, verbose_name='JenisKategori')),
            ],
        ),
        migrations.AddField(
            model_name='tblattachment',
            name='JenisKategoriID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Penilaian.TblRefAttachment'),
        ),
    ]
