# Generated by Django 2.0.6 on 2018-12-11 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Penilaian', '0010_auto_20181205_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbljadual',
            name='TarikhMula',
        ),
        migrations.RemoveField(
            model_name='tbljadual',
            name='TarikhTamat',
        ),
    ]
