# Generated by Django 2.0.6 on 2018-11-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pentadbir', '0001_initial'),
        ('Urusetia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsesi',
            name='SistemID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.TblSistem'),
            preserve_default=False,
        ),
    ]
