# Generated by Django 2.0.6 on 2018-11-23 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0002_tblsesi_sistemid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblKomponen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodKomponen', models.CharField(max_length=10, verbose_name='KodKomponen')),
                ('NamaKomponen', models.CharField(max_length=60, verbose_name='NamaKomponen')),
                ('Pemberat', models.IntegerField(default=0, verbose_name='Pemberat')),
                ('KomponenID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.TblSesi')),
            ],
        ),
    ]
