# Generated by Django 2.1.4 on 2018-12-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0002_auto_20181214_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesi',
            name='TarikhMula',
            field=models.DateTimeField(blank=True, default=None, verbose_name='TarikhMula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sesi',
            name='TarikhMulaAudit',
            field=models.DateTimeField(blank=True, default=None, verbose_name='TarikhMulaAudit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sesi',
            name='TarikhTamat',
            field=models.DateTimeField(blank=True, default=None, verbose_name='TarikhTamat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sesi',
            name='TarikhTamatAudit',
            field=models.DateTimeField(blank=True, default=None, verbose_name='TarikhTamatAudit'),
            preserve_default=False,
        ),
    ]
