# Generated by Django 2.1.4 on 2018-12-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0003_auto_20181219_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesi',
            name='Status',
            field=models.IntegerField(choices=[(0, 'TIDAK AKTIF'), (1, 'AKTIF')], default=0, verbose_name='StatusSesi'),
        ),
    ]
