# Generated by Django 2.0.6 on 2018-11-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0003_tblkomponen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblkomponen',
            old_name='KomponenID',
            new_name='SesiID',
        ),
    ]
