# Generated by Django 2.0.6 on 2018-11-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0004_auto_20181123_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblSkala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deskripsi', models.CharField(max_length=50, verbose_name='Deskripsi')),
                ('NilaiSkala', models.IntegerField(default=1, verbose_name='NilaiSkala')),
            ],
        ),
    ]
