# Generated by Django 2.1.4 on 2018-12-20 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0004_auto_20181219_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesi',
            name='SistemID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.Sistem'),
        ),
    ]
