# Generated by Django 2.0.6 on 2018-11-23 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0005_tblskala'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblSubKomponen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubKodKomponen', models.CharField(max_length=10, verbose_name='SubKodKomponen')),
                ('NamaSubKomponen', models.CharField(max_length=100, verbose_name='NamaSubKomponen')),
                ('Pemberat', models.IntegerField(default=0, verbose_name='Pemberat')),
                ('KomponenID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.TblKomponen')),
                ('SkalaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.TblSkala')),
            ],
        ),
    ]
