# Generated by Django 2.0.6 on 2018-12-04 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0006_tblsubkomponen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblJawapan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeskripsiJawapan', models.CharField(max_length=100, verbose_name='DeskripsiJawapan')),
                ('SkalaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.TblSkala')),
            ],
        ),
        migrations.CreateModel(
            name='TblSoalan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoSoalan', models.CharField(max_length=10, verbose_name='NoSoalan')),
                ('DeskripsiSoalan', models.CharField(max_length=100, verbose_name='DeskripsiSoalan')),
                ('Status', models.IntegerField(default=1, verbose_name='Statussoalan')),
                ('KomponenID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.TblKomponen')),
            ],
        ),
        migrations.AddField(
            model_name='tbljawapan',
            name='SoalanID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.TblSoalan'),
        ),
    ]
