# Generated by Django 2.0.6 on 2018-12-04 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0007_auto_20181204_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAuditee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaAuditee', models.CharField(max_length=100, verbose_name='NamaAuditee')),
                ('IDStatus', models.IntegerField(default=1, verbose_name='IDStatusAuditee')),
            ],
        ),
        migrations.CreateModel(
            name='TblSubAuditee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaSubAuditee', models.CharField(max_length=100, verbose_name='NamaSubAuditee')),
                ('IDStatus', models.IntegerField(default=1, verbose_name='IDStatusSubAuditee')),
                ('AuditeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.TblAuditee')),
            ],
        ),
    ]
