# Generated by Django 2.0.6 on 2018-12-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pentadbir', '0004_uperanan'),
        ('Urusetia', '0008_tblauditee_tblsubauditee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblauditee',
            name='IDStatus',
        ),
        migrations.RemoveField(
            model_name='tblsubauditee',
            name='IDStatus',
        ),
        migrations.AddField(
            model_name='tblauditee',
            name='SistemID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.TblSistem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblauditee',
            name='Status',
            field=models.IntegerField(default=1, verbose_name='StatusAuditee'),
        ),
        migrations.AddField(
            model_name='tblsubauditee',
            name='Status',
            field=models.IntegerField(default=1, verbose_name='StatusSubAuditee'),
        ),
    ]
