# Generated by Django 2.0.6 on 2018-12-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0009_auto_20181205_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsesi',
            name='TarikhMulaAudit',
            field=models.DateField(max_length=60, verbose_name='TarikhMulaAudit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblsesi',
            name='TarikhTamatAudit',
            field=models.DateField(max_length=60, verbose_name='TarikhTamatAudit'),
            preserve_default=False,
        ),
    ]
