# Generated by Django 2.0.6 on 2018-12-11 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0011_auto_20181211_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblrefskala',
            name='SubKodKomponenID',
        ),
    ]
