# Generated by Django 2.0.6 on 2018-12-11 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0012_remove_tblrefskala_subkodkomponenid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbljawapan',
            name='SkalaID',
        ),
    ]
