# Generated by Django 2.0.6 on 2018-12-11 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0013_remove_tbljawapan_skalaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblrefskala',
            name='NamaSkala',
        ),
        migrations.RemoveField(
            model_name='tblrefskala',
            name='Status',
        ),
    ]
