# Generated by Django 2.0.6 on 2018-12-11 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0014_auto_20181211_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblRefSkala',
            new_name='TblSkala',
        ),
        migrations.AddField(
            model_name='tblsubkomponen',
            name='SkalaID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Urusetia.TblSkala'),
            preserve_default=False,
        ),
    ]
