# Generated by Django 2.0.6 on 2018-12-11 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0015_auto_20181211_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblRefSkala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaSkala', models.CharField(max_length=50, verbose_name='NamaSkala')),
                ('Deskripsi', models.CharField(max_length=50, verbose_name='Deskripsi')),
                ('NilaiSkala', models.IntegerField(default=1, verbose_name='NilaiSkala')),
                ('Status', models.IntegerField(default=1, verbose_name='Status')),
            ],
        ),
        migrations.RemoveField(
            model_name='tbljawapan',
            name='SoalanID',
        ),
        migrations.RemoveField(
            model_name='tblsubkomponen',
            name='SkalaID',
        ),
        migrations.DeleteModel(
            name='TblJawapan',
        ),
        migrations.DeleteModel(
            name='TblSkala',
        ),
        migrations.AddField(
            model_name='tblrefskala',
            name='SubKodKomponenID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.TblSubKomponen'),
        ),
    ]
