# Generated by Django 2.0.6 on 2018-12-11 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0016_auto_20181211_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblJawapan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeskripsiJawapan', models.CharField(max_length=100, verbose_name='DeskripsiJawapan')),
                ('SoalanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Urusetia.TblSoalan')),
            ],
        ),
    ]
