# Generated by Django 2.0.6 on 2018-12-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0017_tbljawapan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsesi',
            name='TarikhMula',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='TarikhMula'),
        ),
        migrations.AlterField(
            model_name='tblsesi',
            name='TarikhMulaAudit',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='TarikhMulaAudit'),
        ),
        migrations.AlterField(
            model_name='tblsesi',
            name='TarikhTamat',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='TarikhTamat'),
        ),
        migrations.AlterField(
            model_name='tblsesi',
            name='TarikhTamatAudit',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='TarikhTamatAudit'),
        ),
    ]
