# Generated by Django 2.0.6 on 2018-12-11 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Urusetia', '0019_tbljawapan_nojawapan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblrefskala',
            name='SubKodKomponenID',
        ),
        migrations.AddField(
            model_name='tblsubkomponen',
            name='RefSkalaID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Urusetia.TblRefSkala'),
            preserve_default=False,
        ),
    ]
