# Generated by Django 2.0.6 on 2018-11-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblSistem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaSistem', models.CharField(max_length=200, verbose_name='NamaSistem')),
                ('Tahun', models.IntegerField(verbose_name='Tahun')),
                ('Status', models.IntegerField(default=1, verbose_name='Status')),
                ('PemilikSistem', models.CharField(max_length=200, verbose_name='PemilikSistem')),
            ],
        ),
    ]
