# Generated by Django 2.1.2 on 2018-12-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pentadbir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refperanan',
            name='Status',
            field=models.IntegerField(default=1, verbose_name='Status'),
        ),
    ]
