# Generated by Django 2.1.4 on 2018-12-26 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pentadbir', '0002_refperanan_status'),
        ('Pentadbir', '0002_peranan_nokpten'),
    ]

    operations = [
    ]
