# Generated by Django 2.0.6 on 2018-11-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pentadbir', '0002_uprofil'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefPeranan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Peranan', models.CharField(max_length=100, verbose_name='Peranan')),
                ('KodPeranan', models.IntegerField(default=1, verbose_name='KodPeranan')),
                ('Keterangan', models.CharField(max_length=200, verbose_name='Keterangan')),
            ],
        ),
    ]
