# Generated by Django 2.1.4 on 2018-12-21 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pentadbir', '0002_peranan_nokpten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peranan',
            name='Sistem',
        ),
    ]
