# Generated by Django 2.0.6 on 2018-11-28 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pentadbir', '0003_refperanan'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPeranan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Peranan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.RefPeranan')),
                ('Sistem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.TblSistem')),
                ('UProfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.UProfil')),
            ],
        ),
    ]
