# Generated by Django 2.1.4 on 2018-12-21 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pentadbir', '0003_remove_peranan_sistem'),
    ]

    operations = [
        migrations.AddField(
            model_name='peranan',
            name='Sistem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pentadbir.Sistem'),
            preserve_default=False,
        ),
    ]
