# Generated by Django 2.1.4 on 2018-12-21 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pentadbir', '0004_peranan_sistem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peranan',
            name='UProfil',
        ),
    ]
