# Generated by Django 2.1.4 on 2018-12-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pentadbir', '0005_remove_peranan_uprofil'),
    ]

    operations = [
        migrations.AddField(
            model_name='peranan',
            name='Nama',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
